#!/bin/env bash
# HerbstluftWM script  --- Get's frame gap value and increases or
# decreases it's value according to given parameter. Min val 0.
#
# Copyright (c) 2023  Bruno Boal <bruno.boal@tutanota.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


current_value=$(herbstclient get frame_gap)
new_value=$(("${current_value}" + "$1:-0"))
[[ "${new_value}" -ge 0 ]] && herbstclient set frame_gap "$new_value"
