#!/usr/bin/env bash

hc_dir="$HOME/.config/herbstluftwm"

hc() { herbstclient "$@";}
hc emit_hook reload

# multi monitor setup {{{1
#hc set_monitors 1920x1080+0+0 inverted 1200x1920+1920+240 left 1920x1080+0+1080
xrandr --output DP-1 --off \
       --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate inverted \
       --output DP-2 --off \
       --output HDMI-2 --off \
       --output DP-3 --off \
       --output DP-2-8 --mode 1920x1200 --pos 1920x240 --rotate left \
       --output DP-2-1 --primary --mode 1920x1080 --pos 0x1080 --rotate normal &
# }}}1

# init {{{1
xsetroot -xcf "$HOME/.local/share/icons/volantes_light_cursors/cursors/left_ptr" 17 -solid "#000000"

startup_bin=("unclutter" \
	     "picom -b" \
	     "nm-applet" \
	     "redshift")

for bin in "${startup_bin[@]}"; do
   pidof "${bin%% *}" || "${bin}" &
done

# Setting Xresources
presentHour=$(date +%k)
if [[ -n $DISPLAY && -n $XDG_VTNR ]]; then 
   xrdb -DHOUR_OF_DAY="$presentHour" -load "$HOME"/.Xresources
fi

# }}}1

# wallpapers {{{1
# wallpapers="$HOME"/.config/wallpapers
# xwallpaper --output DP-2-1 --center "$wallpapers"/wallhaven-767m53.jpg \
#            --output HDMI-1 --center "$wallpapers"/wallhaven-j3ov5w_1920x1080.png \
# 	   --output DP-2-8 --center "$wallpapers"/wallhaven-wq8ewp_1200x1920.png
# }}}1

# panel {{{1
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" "$monitor" &
# done
# }}}1

### keybindings {{{1
# remove all existing keybindings
hc keyunbind --all

# Alt and Super definition {{{2
Alt=Mod1    
Super=Mod4  
Hyper=Mod3  
# }}}2

hc keybind $Hyper-$Alt-q quit
hc keybind $Hyper-$Alt-r reload
hc keybind $Hyper-q close

# launching programs
hc keybind $Super-Return spawn "${TERMINAL:-xterm}"
hc keybind $Hyper-w spawn firefox
hc keybind $Hyper-e spawn emacs
hc keybind $Hyper-f spawn thunar
hc keybind $Hyper-r spawn "$hc_dir/dmenu_run_hlwm_v2"
hc keybind $Hyper-Return spawn rofi -show window -modi window -show-icons

# splitting frames
# create an empty frame at the specified direction
hc keybind $Hyper-u      split   bottom  0.5
hc keybind $Hyper-o      split   right   0.5
# let the current frame explode into subframes
hc keybind $Hyper-Control-space split explode

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Hyper-h    focus left
hc keybind $Hyper-j    focus down
hc keybind $Hyper-k    focus up
hc keybind $Hyper-l    focus right

# moving clients in tiling and floating mode
hc keybind $Hyper-Control-h  or / shift left  / \
   chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Hyper-Control-j  or / shift down  / \
   chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $Hyper-Control-k  or / shift up    / \
   chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $Hyper-Control-l  or / shift right / \
   chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# resizing frames and floating clients
resizestep=0.01
hc keybind $Hyper-Left     resize left +$resizestep
hc keybind $Hyper-Down     resize down +$resizestep
hc keybind $Hyper-Up       resize up +$resizestep
hc keybind $Hyper-Right    resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
   hc add "${tag_names[$i]}"
   key="${tag_keys[$i]}"
   if [ -n "$key" ] ; then
       hc keybind "$Hyper-$key" use_index "$i"
       hc keybind "$Hyper-Shift-$key" move_index "$i"
   fi
done

# cycle through tags
hc keybind $Hyper-period use_index +1 --skip-visible
hc keybind $Hyper-comma  use_index -1 --skip-visible

# layouting
hc keybind $Hyper-x remove
hc keybind $Hyper-f floating toggle
hc keybind $Hyper-z fullscreen toggle
hc keybind $Hyper-Shift-f set_attr clients.focus.floating toggle
hc keybind $Hyper-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Hyper-Shift-n set_attr clients.focus.minimized true
hc keybind $Hyper-Shift-m jumpto last-minimized
# Snippet to maximize all minimized windows
hc keybind $Hyper-Shift-u \
   substitute FOCUS "tags.focus.name" \
   foreach CLIENT clients. \
      sprintf MINATT "%c.minimized" CLIENT \
      sprintf TAGATT "%c.tag" CLIENT and \
	, compare MINATT "=" "true" \
	, compare TAGATT "=" FOCUS \
	, set_attr MINATT false
hc keybind $Hyper-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Hyper-space \
   or , and . compare tags.focus.curframe_wcount = 2 \
	    . cycle_layout +1 vertical horizontal max grid \
      , cycle_layout +1

# mouse {{{2
hc mouseunbind --all
hc mousebind $Super-Button1 move
hc mousebind $Super-Button2 zoom
hc mousebind $Super-Button3 resize
# }}}2

# focus
hc keybind $Hyper-BackSpace cycle
hc keybind $Hyper-Tab	    cycle_all +1
hc keybind $Hyper-Shift-Tab cycle_all -1
hc keybind $Hyper-c	    cycle_monitor
hc keybind $Hyper-i         jumpto urgent

# gap space
hc keybind $Hyper-g    spawn "${hc_dir}"/_resize_gap +1
hc keybind $Hyper-Shift-g spawn "${hc_dir}"/_resize_gap -1


###}}}1

# theme settings {{{2
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_width 0
hc set show_frame_decorations 'focused_if_multiple'
hc set always_show_frame on
hc set frame_bg_transparent off
hc set frame_transparent_width 4
hc set frame_padding 0
hc set frame_gap 0
hc set window_gap 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 0

# TODO
hc attr theme.border_width 4 # must have diff >=1 from inner_width
hc attr theme.inner_width 1  # check previous note

#floating windows
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black

### Colors {{{3
# Daytime and Nightime
day=6;night=17
if [[ $(date +%k) -ge "${day}" && $(date +%k) -lt "${night}" ]]; then
   cursorcolor='#386578'
   background='#ffffff'
   # foreground='#000000'
   color1='#a60000'
   color2='#005e00'
   color4='#0031a9'
   color7='#bfbfbf'
   color12='#2544bb'
   color13='#5317ac'
else
   cursorcolor='#386578'
   background='#000000'
   # foreground='#ffffff'
   color1='#ff8059'
   color2='#44bc44'
   color4='#2fafff'
   color7='#bfbfbf'
   color12='#79a8ff'
   color13='#b6a0ff'
fi

# title
hc attr theme.title_when never # when `never`, the `theme.title` can be commented
# hc attr theme.title_height 15
hc attr theme.title_font 'SudoVarNerdFontPSPLWEAM Nerd Font Mono:size=13'  # example using Xft
# hc attr theme.title_depth 3  # space below the title's baseline
# hc attr theme.title_color  "${background}"
# hc attr theme.normal.title_color  "${foreground}"

# frame
hc set frame_border_active_color "${color12}"
hc set frame_border_normal_color '#00000000'
hc set frame_bg_normal_color "${background}"
hc set frame_bg_active_color '#1f326f' 


# active, normal, urgent
hc attr theme.active.color "${color12}"
hc attr theme.active.inner_color "${color4}"
hc attr theme.normal.color "${background}"
hc attr theme.normal.inner_color "${color1}"
hc attr theme.urgent.color "${color13}"
hc attr theme.urgent.inner_color "${color13}"
# copy inner color to outer_color
for state in active urgent normal ; do
   hc substitute C theme.${state}.inner_color \
	      attr theme.${state}.outer_color C
done


# tab
hc attr theme.tab_color "${color4}"
hc attr theme.active.tab_color "${color12}"
hc attr theme.active.tab_outer_color "${color2}"
hc attr theme.active.tab_title_color "${color7}"

hc attr theme.inner_color "${background}" # should match background color
hc attr theme.background_color "${cursorcolor}"
### }}}3
## }}}2

## USER {{{2
hc set auto_detect_panels on
hc set tabbed_max true
hc set update_dragged_clients true

##}}}2

# rules {{{1
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm.*|st)' focus=on # give focus to most common terminals
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on
# }}}1

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

hc detect_monitors
